// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onnodkuthpswanqfrqot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubm9ka3V0aHBzd2FucWZycW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTkwMzYsImV4cCI6MjA2MjMzNTAzNn0.rb6Vt0aqIfi3ycxFwB0sDFfhsSosjeKiwP7ms52Bp4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);